### ISSUE TITLE
Wyrzućcie yarn.lock z gita

### ISSUE THREAD

**Issue by wojciechbator** [sejseen/BeerHangoutApp#10]
Zapominam o tym cały czas - można spokojnie to wyrzucić z gita, to się buduje. Ponadto unikniemy commitów rzędu +5000 -3000 linie kodu.

**Comment by sejseen** [comment]
Zrobione, zaakcaptuj tylko pull requesta ;)

**Comment by wojciechbator** [comment]
ok
